Fix a MinGW link error
Fix the following MinGW link error:

libtool: link: x86_64-w64-mingw32-gcc -Wall -W -Wall -Wextra -Werror -Wno-sign-compare -Wno-unused-function -Wno-unused-parameter -D__USE_MINGW_ANSI_STDIO -D__USE_MINGW_ANSI_STDIO -o .libs/sg_timestamp.exe sg_timestamp.o  ../lib/.libs/libsgutils2.dll.a -L/usr/local/lib
/usr/bin/x86_64-w64-mingw32-ld: sg_turs.o:sg_turs.c:(.text+0x73d): undefined reference to `nanosleep'

Signed-off-by: Bart Van Assche <bvanassche@acm.org>