Fix build with gcc 4.8
Check if stdatomic.h is available before using it to fix the following
build failure raised since version 1.46 and
https://github.com/hreinecke/sg3_utils/commit/e9445f4efc012d37809342ba21f16360a0208f06:

sgp_dd.c:67:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^

Fixes:
 - http://autobuild.buildroot.org/results/2f531a187dd8e4c709bc0d81f8d4cb36ef5f5437

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>